### ISSUE TITLE
Does not work (list index out of range)

### ISSUE THREAD

**Issue by callesg** [brycedrennan/eulerian-magnification#18]
I cant get it to work:
```
Loading eulerian_source_videos/baby.mp4
Traceback (most recent call last):
  File "replicate_study.py", line 84, in <module>
    replicate_study()
  File "replicate_study.py", line 75, in replicate_study
    pyramid_levels=pyramid_levels
  File "/home/calle/eulerian-magnification/eulerian_magnification/base.py", line 27, in eulerian_magnification
    vid_data = collapse_laplacian_video_pyramid(vid_pyramid)
  File "/home/calle/eulerian-magnification/eulerian_magnification/pyramid.py", line 68, in collapse_laplacian_video_pyramid
    return pyramid[0]
IndexError: list index out of range
```

Here is the exact way i tried to use it from a fresh ubuntu 1604 vm.

```
    6  sudo apt install python3-pip
    7  sudo apt install git
   12  git clone https://github.com/brycedrennan/eulerian-magnification
   13  cd eulerian-magnification/
   16  pip3 install -r requirements.txt 
   19  pip3 install opencv
   22  pip3 install matplotlib
   25  sudo apt-get install python3-tk
   28  sudo python3 setup.py install
   31  pip3 install numpy scipy matplotlib
   32  python3 replicate_study.py 
   33  history
```

**Comment by brycedrennan** [comment]
Yes I haven't done significant work on this for a very long time. Does not surprise me that it's broken. If you figure out the issue I welcome a pull request.

**Comment by brycedrennan** [comment]
I've added a dockerfile which should allow you to play with this without worrying about installing dependencies correctly
